Repository CrowdStrike/aws-ec2-image-builder, pull requests merged in 2025-01, with the labels that each got.

#12 Added component and windows installation script.
  README.md
  components/crowdstrike-falcon-install-windows.yml
  scripts/deploy-falcon-windows.ps1
Labels: enhancement

#14 chore: bump v1.2.0
  components/crowdstrike-falcon-install-linux.yml
  components/crowdstrike-falcon-install-windows.yml
Labels: release

#15 chore: update description and region for cli
  README.md
  components/crowdstrike-falcon-install-linux.yml
  components/crowdstrike-falcon-install-windows.yml
Labels: documentation, enhancement

#16 chore: bump v1.2.1
  components/crowdstrike-falcon-install-linux.yml
  components/crowdstrike-falcon-install-windows.yml
Labels: release

#17 chore: bumping due to ec2 ib issue
  components/crowdstrike-falcon-install-linux.yml
  components/crowdstrike-falcon-install-windows.yml
Labels: release
